config/routes.rb
Rails.application.routes.draw do
    get '/' => 'characters#index'
    resources :characters
end

app/models/character.rb
class Character < ActiveRecord::Base
	def find_similar
		@characters_matched = Character.where("(favourite_food == ? OR programming_language == ?)AND name != ?", self.favourite_food, self.programming_language, self.name)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
	def index
		@characters = Character.all		
	end
	def show
		begin
			@character = Character.find params[:id]
			@characters = @character.find_similar
		rescue ActiveRecord::RecordNotFound
			render 'no_character_found'
		end
	end
	def new
		@character = Character.new	
	end
	def edit
		@character = Character.find params[:id]
	end
	def create
		@character = Character.new(character_params)
		@character.save
		redirect_to character_path(@character)
	end
	def update
		@character = Character.find(params[:id])
		@character.update(character_params)
		redirect_to character_path(@character)
	end
	def destroy
		@character = Character.find(params[:id])
		@character.destroy
		redirect_to character_path
	end
	
	private

	def character_params
		params.require(:character).permit(:name, :birth_year, :age, :favourite_food, :programming_language, :image, :hobbies)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/edit.html.erb
<h3>Editing character:</h3>

<div class="container">
  <div class="row">
    <div class="column col-xs-12 col-md-4">

      <%= form_for @character do |c| %>

      <p>
        <%= c.label :name %><br>
        <%= c.text_field :name %>
      </p>

      <p>
        <%= c.label :birth_year %><br>
        <%= c.number_field :birth_year %>
      </p>

      <p>
        <%= c.label :age %><br>
        <%= c.number_field :age %>
      </p>

      <p>
        <%= c.label :favourite_food %><br>
        <%= c.text_field :favourite_food %>
      </p>

      <p>
        <%= c.label :programming_language %><br>
        <%= c.text_area :programming_language %>
      </p>

      <p>
        <%= c.label :hobbies %><br>
        <%= c.text_area :hobbies %>
      </p>

      <p>
        <%= c.label :image %><br>
        <%= c.text_field :image %>
      </p>

      <p>
        <%= c.submit %>
      </p>

      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="column col-xs-6 col-md-4">
      <%= link_to 'Back to characters', characters_path %></p>
    </div>
  </div>
</div>

app/views/characters/index.html.erb
<div class="container">
	<h1>CHARACTERS</h1>
</div>

<div class="container">
	<div class="row">
		<div class="col-xs-12 col-md-4">
			<% @characters.each do |character| %>
				<p><img src="<%= character.image%>" width="24">
				<%= character.name %><br>
				<%= link_to 'See', character_path(character) %></p>
			<% end %>
		</div>

		<div class="col-xs-12 col-md-8">
			<img id="rocket" src="http://adamquattro.com/main/wp-content/uploads/2014/02/render.png">
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12">
			<p><%= link_to 'New character', new_character_path %></p>
		</div>
	</div>
</div>

app/views/characters/new.html.erb
<h3>New character:</h3>

<%= form_for @character do |c| %>

<p>
  <%= c.label :name %><br>
  <%= c.text_field :name %>
</p>

<p>
  <%= c.label :birth_year %><br>
  <%= c.number_field :birth_year %>
</p>

<p>
  <%= c.label :age %><br>
  <%= c.number_field :age %>
</p>

<p>
  <%= c.label :favourite_food %><br>
  <%= c.text_field :favourite_food %>
</p>

<p>
  <%= c.label :programming_language %><br>
  <%= c.text_area :programming_language %>
</p>

<p>
  <%= c.label :hobbies %><br>
  <%= c.text_area :hobbies %>
</p>

<p>
  <%= c.label :image %><br>
  <%= c.text_field :image %>
</p>

<p>
  <%= c.submit %>
</p>

<% end %>

<%= link_to 'Volver a personajes', characters_path %></p>

app/views/characters/no_character_found.html.erb
<h3>Character not found</h3>

app/views/characters/show.html.erb
<div class="container">
	<h3><%= @character.name %></h3>
</div>

<div class="container">
	<div class="row">
		<div class="column col-xs-12 col-md-4">

			<p><b>Birth year:</b>
			<%= @character.birth_year %><br>
			</p>

			<p><b>Age:</b>
			<%= @character.age %><br>
			</p>

			<p><b>Favourite food:</b>
			<%= @character.favourite_food %><br>
			</p>

			<p><b>Programming language:</b>
			<%= @character.programming_language %><br>

			<p><b>Hobbies:</b>
			<%= @character.hobbies %>
			</p>

			<hr>

			<p><%= link_to 'Edit character', edit_character_path(@character) %></p>
			<p><%= link_to 'Back to characters', characters_path %></p>
		</div>

		<div class="column col-xs-12 col-md-4">
			<img src="<%= @character.image%>">
		</div>

		<div class="column col-xs-6 col-md-4">

			<h4>Matches:</h4>

			<% @characters.each do |character| %>
				<p><img src="<%= character.image%>" width="24">
				<%= character.name %><br>
				<%= link_to 'See', character_path(character) %></p>
			<% end %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Futurama</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<!-- External JavaScript -->
<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.11.2.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

</body>
</html>